/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "2.1.3"

#define QTCHARTS_VERSION 0x020103

#endif // QT_QTCHARTS_VERSION_H
